#ifndef PICO_PIN_ENUMERATION_S_H
#define PICO_PIN_ENUMERATION_S_H

#include <stdio.h>
#include "pico/stdlib.h"

enum pico_pins {
  UNDEFINED = -1,
  GPIO_ZERO,
  GPIO_ONE,
  GPIO_TWO,
  GPIO_THREE,
  GPIO_FOUR,
  GPIO_FIVE,
  GPIO_SIX,
  GPIO_SEVEN,
  GPIO_EIGHT,
  GPIO_NINE,
  GPIO_TEN,
  GPIO_ELEVEN,
  GPIO_TWELVE,
  GPIO_THIRTEEN,
  GPIO_FOURTEEN,
  GPIO_FIFTEEN,
  GPIO_SIXTEEN,
  GPIO_SEVENTEEN,
  GPIO_EIGHTEEN,
  GPIO_NINETEEN,
  GPIO_TWENTY,
  GPIO_TWENTY_ONE,
  GPIO_TWENTY_TWO,
  GPIO_TWENTY_SIX = 26,
  GPIO_TWENTY_SEVEN = 27, 
  GPIO_TWENTY_EIGHT = 28
};


#endif